apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: <your-account-id>.dkr.ecr.<region>.amazonaws.com/<your-repo>:latest
        ports:
        - containerPort: 8080   # yaha apne app ka port daalo
        env:
        - name: DB_HOST
          value: "movie-app.cx4smawkyvs9.ap-south-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASS
          value: "Shubham1997"
        - name: DB_NAME
          value: "movie-app"
